# Kotlin
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
kotlin.daemon.jvmargs=-Xmx4g

# Gradle
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Android
android.useAndroidX=true
android.nonTransitiveRclass=true

# Compose
org.jetbrains.compose.experimental.uikit.enabled=true

# KMP
kotlin.native.ignoreDisabledTargets=true

# KMMBridge
GITHUB_PUBLISH_TOKEN=<REDACTED>
GITHUB_REPO=ShadAdman/Whisper

# Maven Publish
PROJECT_GROUP=io.github.shadadman
PROJECT_VERSION_NAME=0.90.0
POM_ARTIFACT_ID=whisper
POM_NAME=Whisper
POM_DESCRIPTION=A secure, decentralized, and ultra-low-latency communication protocol using ultrasound acoustic waves.
POM_URL=https://github.com/ShadAdman/Whisper
POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=shadadman
POM_DEVELOPER_NAME=Shad Adman
POM_DEVELOPER_EMAIL=adman.shadman@gmail.com
SCM_CONNECTION=scm:git:github.com/ShadAdman/Whisper.git
SCM_DEVELOPER_CONNECTION=scm:git:ssh://github.com/ShadAdman/Whisper.git
